@echo off
echo Auto git push script started (every 5 seconds)...
:loop
echo [%date% %time%] Running git push...
git push
echo [%date% %time%] git push finished, waiting 5 seconds...
timeout /t 5 /nobreak >nul
goto loop